swagger: "2.0"
info:
  description: "API eMJPM"
  version: "1.0.0"
  title: "API eMJPM"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "contact@emjpm.beta.gouv.fr"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "api.emjpm.num.social.gouv.fr"
schemes:
- "https"
paths:
  /auth/login:
    post:
      summary: "login"
      description: "login to receive an auth cookie"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "user credentials"
        required: true
        schema:
          $ref: "#/definitions/Login"
      responses:
        401:
          description: "Unauthorized"
        200:
          description: "success"

securityDefinitions:
  BasicAuth:
    type: basic
  api_key:
    type: "apiKey"
    in: "header"
    name: X-API-Key
definitions:
  Login:
    type: "object"
    properties:
      username:
        type: "string"
      password:
        type: "string"
